== OpenBSD PF cheatsheet

- General PFCTL Commands

....
pfctl -d # disable packet-filtering
pfctl -e # enable packet-filtering
pfctl -q # run quiet
pfctl -vv # run even more verbose
....

- Loading PF Rules

....
pfctl -f /etc/pf.conf # load /etc/pf.conf
pfctl -n -f /etc/pf.conf # parse /etc/pf.conf, but dont load it
pfctl -R -f /etc/pf.conf # load only the FILTER rules
pfctl -N -f /etc/pf.conf # load only the NAT rules
pfctl -O -f /etc/pf.conf # load only the OPTION rules
....

- Clearing PF Rules & Counters

....
pfctl -F all # flush ALL
pfctl -F rules # flush only the RULES
pfctl -F queue # flush only queue’s
pfctl -F nat # flush only NAT
pfctl -F info # flush all stats that are not part of any rule.
pfctl -z # clear all counters
....
_**Note:** flushing rules do not touch any existing stateful connections_


- Get PF Information

....
pfctl -s rules # show filter information
pfctl -v -s rules # show filter information for what FILTER rules hit..
pfctl -vvsr # show filter information as above and prepend rule numbers
pfctl -v -s nat # show NAT information, for which NAT rules hit..
pfctl -s nat -i xl1 # show NAT information for interface xl1
pfctl -s queue # show QUEUE information
pfctl -s label # show LABEL information
pfctl -s state # show contents of the STATE table
pfctl -s info # show statistics for state tables and packet normalization
pfctl -s all # show everything
....

- Maintaining PF Tables

....
pfctl -t blacklist -T show # show table blacklist
pfctl -vvsTables # view global information about all tables
pfctl -t blacklist -T add 10.100.1.1 # add entry to table blacklist
pfctl -t blacklist -T add 10.100.1.0/24 # add a network to table blacklist
pfctl -t blacklist -T delete 10.100.1.0./24 # delete nework from table blacklist
pfctl -t blacklist -T flush # remove all entries from table blacklist
pfctl -t blacklist -T kill # delete table blacklist entirely
pfctl -t blacklist -T replace -f /etc/blacklist # reload table blacklist on the fly
pfctl -t blacklist -T test 10.100.1.150 # check IP is present in the table blacklist
pfctl -T load -f /etc/pf.conf # load a new table definition
pfctl -t blacklist -T show -v # output stats for each ip address in table blacklist
pfctl -t blacklist -T zero # reset all counters for table blacklist
....
